spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: password
  application:
    name: VerveAssignment

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
  
  jpa:
    hibernate:
      ddl-auto: create-drop
      
server:
  port: 1321
  
csv:
  file:
    path: src/main/resources/promotions.csv
    
chunk:
  size: 5000

---
spring:
    config:
        activate:
            on-profile: docker

csv:
  file:
    path: promotions.csv